// =====================================================================
//  GALDERA-BANKUA · Filosofiaren Historia, 1. blokea (USaP)
// ---------------------------------------------------------------------
//  Galdera bakoitza:
//    m    : galdera (testua)
//    a    : erantzun-aukerak (2-4)
//    z    : erantzun zuzenaren posizioa (0 = lehena)
//    mota : 'aukera' | 'eg' (egia/gezurra) | 'aipua' (nork esan zuen?)
//    az   : azalpena (erantzuna erakustean agertzen da)
//  Aukeren ordena jokoan nahasten da (egia/gezurra izan ezik).
//  Galdera berriak gehitzeko, kopiatu bloke bat eta aldatu testua.
// =====================================================================

window.LOGOS_MAILAK = [
  // ===================================================================
  {
    id: 'mileto', zenbakia: 1, izena: 'Mileto',
    gaia: 'Mitotik logosera · Presokratikoak',
    ikonoa: '🌊', kolorea: '#22d3ee',
    deskribapena: 'Filosofiaren jaiotza: mitoetatik arrazoira eta lehen naturaren filosofoak.',
    galderak: [
      { mota: 'aukera', m: 'Noiz eta non jaio zen filosofia?',
        a: ['K.a. VI. mendeko Grezian', 'K.a. IV. mendeko Erroman', 'K.a. VI. mendeko Egipton', 'K.o. I. mendeko Alejandrian'], z: 0,
        az: 'Filosofia K.a. VI. mendean jaio zen, Grezian: Mediterraneo ekialdean eta Asia Txikian zabaldutako hiri-estatuen multzoan (Helade).' },
      { mota: 'aukera', m: 'Nola deitzen zieten greziarrek euren hiri-estatu txiki eta independenteei?',
        a: ['Polis', 'Stoa', 'Arkhe', 'Logos'], z: 0,
        az: 'Polisak hiri-estatu txiki eta independenteak ziren (Atenas, Mileto, Esparta, Korinto...), kultura eta kosmologia partekatu batek elkartzen zituenak.' },
      { mota: 'aukera', m: 'Hauetako zeinek EZ zuen lagundu filosofia Grezian sortzen?',
        a: ['Errege-jainko baten agintea inperio teokratiko handi batean', 'Herritarren askatasuna eta bizitza publiko partaidetzazkoa', 'Egipto, Mesopotamia eta Persiarekiko kontaktua', 'Idazkera alfabetikoa eta merkataritza-burgesia'], z: 0,
        az: 'Ekialde Hurbileko inperio teokratikoek ez bezala, polisek askatasuna, eztabaida eta arrazoiketa publikoa bultzatu zituzten. Kokapen geografikoak eta teknika berriek ere lagundu zuten.' },
      { mota: 'eg', m: 'Mitoek erantzun itxiak ematen zituzten, tradizioaren autoritatean oinarrituak, eta Homero eta Hesiodo bezalako poetak ez ziren zalantzan jartzen.',
        a: ['Egia', 'Gezurra'], z: 0,
        az: 'Egia. Mitoak ahoz transmititzen ziren eta ez ziren kritikatzen. Logosak, aldiz, azalpen arrazional, koherente eta argudiatuak bilatzen ditu.' },
      { mota: 'aukera', m: 'Zer esan nahi du "logos" hitzak mitotik logoserako bidean?',
        a: ['Diskurtso arrazionala', 'Jainkoen narrazio tradizionala', 'Gauza guztien lehen elementua', 'Hiriko batzar publikoa'], z: 0,
        az: 'Logosa diskurtso arrazionala da: errealitatea arrazoiaren bidez azaltzea, jainkoetara jo gabe.' },
      { mota: 'eg', m: 'Mitotik logoserako trantsizioa berehalakoa eta erabatekoa izan zen.',
        a: ['Egia', 'Gezurra'], z: 1,
        az: 'Gezurra. Denbora luzez pentsamendu mitikoa eta arrazionala elkarrekin bizi izan ziren. Presokratikoek inflexio-puntua markatu zuten.' },
      { mota: 'aukera', m: 'Zer bilatzen zuten presokratikoek, "naturaren filosofoek"?',
        a: ['Arkhea: gauza guztien lehen printzipioa', 'Ongiaren ideia', 'Ataraxia: arimaren lasaitasuna', 'Definizio unibertsalak'], z: 0,
        az: 'Presokratikoen kezka nagusia natura (physis) eta kosmosaren jatorria ziren. Arkhea bilatzen zuten: dena sortu eta eraldatzen duen oinarrizko osagaia.' },
      { mota: 'aukera', m: 'Miletoko Talesen ustez, zein zen arkhea?',
        a: ['Ura', 'Airea', 'Apeirona', 'Zenbakiak'], z: 0,
        az: 'Talesentzat ura zen gauza guztien iturburua, naturako elementu guztietan errepikatzen zen sustantzia.' },
      { mota: 'aukera', m: 'Zer da Anaximandroren "apeirona"?',
        a: ['Elementu zehaztugabe, betiereko eta amaigabea', 'Lau elementuen nahasketa', 'Partikula ikusezin eta zatiezina', 'Airea kondentsatzean sortzen dena'], z: 0,
        az: 'Anaximandrok bere maisu Tales kritikatu zuen: lau elementuak kontrajarriak direnez, bat infinitua balitz beste hirurak ezabatuko lituzke. Horregatik proposatu zuen apeirona.' },
      { mota: 'aukera', m: 'Anaximenesen ustez, nola sortzen dira munduko izate guztiak?',
        a: ['Airearen rarefakzio eta kondentsazioaren bidez', 'Maitasunak lau elementuak elkartzean', 'Atomoak hutsean mugitzean', 'Apeironetik kontrarioak bereiztean'], z: 0,
        az: 'Anaximenesentzat airea zen arkhea, "munduaren arnasa". Rarefakzio eta kondentsazioaren bidez forma ezberdinak hartzen zituen.' },
      { mota: 'aukera', m: 'Pitagoras eta pitagorikoentzat, zer zegoen gauza guztien oinarrian?',
        a: ['Zenbakiak', 'Sua', 'Ura', 'Atomoak'], z: 0,
        az: 'Pitagorikoentzat natura hizkuntza matematikoaz uler zitekeen. Arrazoia erabiliz, zentzumenen subjektibotasuna alde batera utzita, benetako egia (alētheia) ezagutzen zen.' },
      { mota: 'aipua', m: '"Ezin izango zara sekula bi aldiz ibai berean bainatu."',
        a: ['Heraklito', 'Parmenides', 'Tales', 'Demokrito'], z: 0,
        az: 'Heraklitorentzat unibertsoa mugimendu konstantean dago, "jario amaigabe" batean: dena dago transformazioan.' },
      { mota: 'aipua', m: '"Badena bada eta ez dena ez da."',
        a: ['Parmenides', 'Heraklito', 'Anaximandro', 'Pitagoras'], z: 0,
        az: 'Parmenidesek izatearen egonkortasuna defendatu zuen: zentzumenek erakusten diguten aldaketa itxurazkoa baino ez da.' },
      { mota: 'eg', m: 'Heraklitok eta Parmenidesek bat egiten zuten: unibertsoak ordena logiko bat (logos) jarraitzen du eta arrazoiaren bidez ezagut daiteke.',
        a: ['Egia', 'Gezurra'], z: 0,
        az: 'Egia. Biek uste zuten kosmosa gidatua dagoela eta egiazko errealitatea (alētheia) arrazoiaren bidez ezagutzen dela. Aldaketan ez zeuden ados.' },
      { mota: 'aukera', m: 'Zer defendatzen zuten filosofo "monistek"?',
        a: ['Natura elementu nagusi bakar batek gobernatzen duela', 'Lau elementu daudela', 'Ezer ezin dela ezagutu', 'Legeak konbentzioak direla'], z: 0,
        az: 'Monistek elementu nagusi bakarra zegoela uste zuten (arkhea edo logosa). Pluralistek, berriz, oinarrizko elementu ugariren konbinazioa.' },
      { mota: 'aukera', m: 'Zein filosofo pluralistaren ustez dago dena lau elementuz osatuta (ura, sua, airea eta lurra), maitasunaren indarrak elkartuta?',
        a: ['Enpedokles', 'Demokrito', 'Anaximandro', 'Tales'], z: 0,
        az: 'Enpedoklesentzat lau elementuak elkartu edo banatu egiten dira, eta horrela sortzen dira ezagutzen ditugun izate eta fenomenoak.' },
      { mota: 'aukera', m: 'Zer esan nahi du etimologikoki "atomo" hitzak?',
        a: ['Zatiezina', 'Ikusezina', 'Betierekoa', 'Mugikorra'], z: 0,
        az: 'Demokritok "atomo" (zatiezina) deitu zien naturako izateak osatzen dituzten partikula txikienei.' },
      { mota: 'aipua', m: '"Badira munduan koloreak, gozotasuna eta mingotsa. Baina, egiaz, atomoak eta hutsa baino ez da existitzen."',
        a: ['Demokrito', 'Enpedokles', 'Pitagoras', 'Anaximenes'], z: 0,
        az: 'Demokrito atomismo klasikoaren erreferentea da: inolako mikroskopiorik gabe argudiatu zuen dena partikula ikusezin eta zatiezinez osatuta dagoela.' }
    ]
  },

  // ===================================================================
  {
    id: 'agora', zenbakia: 2, izena: 'Agora',
    gaia: 'Sofistak eta Sokrates',
    ikonoa: '🗣️', kolorea: '#ff4d8d',
    deskribapena: 'Periklesen Atenas: erretorika, erlatibismoa eta Sokratesen galderak.',
    galderak: [
      { mota: 'aukera', m: 'Periklesen Atenaseko demokrazian, nortzuk izaten ziren politikoak?',
        a: ['Konbentzitzeko gaitasun handiena zutenak', 'Pertsona jakintsuenak', 'Jainkoek aukeratutakoak', 'Soldadurik ausartenak'], z: 0,
        az: 'Gizonezko libre guztiek bozkatu zezaketen, eta jendaurrean hobekien hitz egiten zekitenak bihurtzen ziren politiko.' },
      { mota: 'aukera', m: 'Zer irakasten zuten sofistek?',
        a: ['Erretorika: hitzaren artea', 'Matematika eta astronomia', 'Medikuntza', 'Dialektika platonikoa'], z: 0,
        az: 'Sofistak erretorika-irakasleak ziren. Politiko izan nahi zuten gazte aberatsei argudio sendoak eraikitzen irakasten zieten.' },
      { mota: 'aukera', m: 'Zein emakumek gidatu zuen emakumeen eskola bat Atenasen, eta Periklesen aholkulari ere izan zen?',
        a: ['Miletoko Aspasia', 'Alejandriako Hipatia', 'Safo', 'Xantipa'], z: 0,
        az: 'Miletoko Aspasia hitz egin eta argudiatzeko gaitasunagatik zen miretsia, eta Periklesen aholkulari izan zen.' },
      { mota: 'aukera', m: 'Zer da sofisten "eszeptizismo epistemologikoa"?',
        a: ['Egia absoluturik ez dagoela eta ezin dela ezagutu', 'Ongia unibertsala dela', 'Zentzumenak beti fidagarriak direla', 'Arimak ideiak gogoratzen dituela'], z: 0,
        az: 'Sofisten arabera ez zegoen gauza guztien gaineko egiarik, eta, beraz, ezin zen ezagutu.' },
      { mota: 'aukera', m: 'Zein sofistak eraman zuen eszeptizismo epistemologikoa muturrera?',
        a: ['Gorgias', 'Sokrates', 'Diogenes', 'Pirron'], z: 0,
        az: 'Gorgiasen ustez, natura aldaketa konstantean dagoenez, ezer ezin zen bere horretan existitu eta, ondorioz, ezer ezin zen ezagutu.' },
      { mota: 'aukera', m: '"Atenasen zuzena den lege bat Espartan guztiz bidegabea izan daiteke." Zein ideia da hau?',
        a: ['Erlatibismo morala', 'Intelektualismo morala', 'Antierlatibismo morala', 'Maieutika'], z: 0,
        az: 'Sofisten erlatibismo moralaren arabera, ongia eta gaizkia kontzeptu subjektiboak dira eta ikuspuntuaren arabera aldatzen dira.' },
      { mota: 'aukera', m: 'Zer da "legeen konbentzionaltasuna"?',
        a: ['Legeak gizakiek sortuak direla eta komenigarritasunaren arabera aldatzen direla', 'Legeak jainkoek emanak direla', 'Legeak naturan idatzita daudela', 'Filosofoek soilik egin ditzaketela legeak'], z: 0,
        az: 'Polisetako legeak gizakiek sortzen dituzte, ez jainkoek. Horregatik ez dira objektiboak, subjektiboak baizik.' },
      { mota: 'eg', m: 'Sokratesek liburu asko idatzi zituen, eta haietatik ezagutzen dugu bere pentsamendua.',
        a: ['Egia', 'Gezurra'], z: 1,
        az: 'Gezurra. Sokratesek ez zuen sekula ezer idatzi. Bere ekarpenak Platonen eta Aristotelesen idatzietatik jaso ditugu.' },
      { mota: 'aukera', m: 'Zer da Sokratesen "antierlatibismo morala"?',
        a: ['Ongia eta justizia objektiboak, unibertsalak eta betierekoak direla', 'Ongia norberaren interesaren araberakoa dela', 'Legeak hiri bakoitzean aldatzen direla', 'Ezer ezin dela ziurtasunez jakin'], z: 0,
        az: 'Sokratesentzat ongia, justizia eta edertasuna definizio unibertsalak dira: gizaki guztientzat berdinak, eta ez dira aldatzen leku batetik bestera.' },
      { mota: 'eg', m: 'Sokratesen ustez, definizio unibertsalak zentzumenen bidez ezagutzen dira.',
        a: ['Egia', 'Gezurra'], z: 1,
        az: 'Gezurra. Definizio unibertsalak gure ariman daude betidanik, eta pentsamenduaren eta arrazoiaren bidez soilik iristen gara haietara.' },
      { mota: 'aukera', m: 'Sokratesen ustez, zergatik jokatzen du norbaitek gaizki?',
        a: ['Ongia zer den ez dakielako', 'Nahita egiten duelako', 'Jainkoek hala erabaki dutelako', 'Legeak hala agintzen duelako'], z: 0,
        az: 'Inork ez du nahita gaizki jokatzen: "dakienak ongi jokatzen du". Gaizki jokatzea ezjakintasunaren seinale da.' },
      { mota: 'aukera', m: 'Nola deitzen zaio bertutea ezagutzarekin lotzeari ("dakienak ongi jokatzen du")?',
        a: ['Intelektualismo morala', 'Erlatibismo morala', 'Dualismo ontologikoa', 'Hilemorfismoa'], z: 0,
        az: 'Intelektualismo moralaren arabera, ongia ezagutzen duenak ongi jokatzen du. Platonek ere jarraitu zion ideia honi.' },
      { mota: 'aukera', m: 'Zertan zetzan Sokratesen "ironia"?',
        a: ['Ezjakinaren itxura egin eta galderen bidez solaskidearen kontraesanak azaleratzean', 'Solaskideei barre egitean', 'Hitzaldi luzeak ematean', 'Gezurrak esanez konbentzitzean'], z: 0,
        az: 'Ironia metodoaren lehen pausua zen: norberaren ezjakintasunaz ohartzea da jakintza eskuratzeko lehen urratsa.' },
      { mota: 'aukera', m: 'Zergatik deitzen zaio Sokratesen metodoari "maieutika"?',
        a: ['Bere ama emagina zelako eta filosofia erditzearekin konparatzen zuelako', 'Mendi baten izena delako', 'Atenaseko eskola baten izena zelako', 'Matematikan oinarritzen zelako'], z: 0,
        az: 'Maieutikaren bidez ez dugu ezer berririk ikasten: barruan ditugun definizio unibertsalak azaleratzen (erditzen) ditugu.' },
      { mota: 'aipua', m: '"Ezer ez dakidala soilik dakit."',
        a: ['Sokrates', 'Gorgias', 'Platon', 'Aristoteles'], z: 0,
        az: 'Sokratesen esaldi ospetsua. Ezjakintasunaz ohartzea da jakinduriaren lehen pausua.' },
      { mota: 'aukera', m: 'Platonen eta Sokratesen ustez, nork agindu behar luke hirian?',
        a: ['Filosofoek: Ongia ezagutzera iritsi diren jakintsuek', 'Konbentzitzeko gaitasun handiena dutenek', 'Aberatsenek', 'Herritar guztiek txandaka'], z: 0,
        az: 'Platonek sofistak kritikatu zituen: agintaria ez da konbentzitzen dakiena izan behar, herritarrik justuena baizik, Ongia ezagutzen duena.' }
    ]
  },

  // ===================================================================
  {
    id: 'akademia', zenbakia: 3, izena: 'Akademia',
    gaia: 'Ideia eta izaera: Platon eta Aristoteles',
    ikonoa: '🏛️', kolorea: '#f5c542',
    deskribapena: 'Ezagutza eta errealitatea: ideien mundua, haitzuloa eta hilemorfismoa.',
    galderak: [
      { mota: 'aukera', m: 'Zer aztertzen du ontologiak?',
        a: ['Errealitatearen izaera', 'Egiazko ezagutza lortzeko bidea', 'Gobernu motak', 'Bertute moralak'], z: 0,
        az: 'Ontologiak errealitatearen izaera aztertzen du; epistemologiak, berriz, egiazko ezagutza eskuratzeko bidea.' },
      { mota: 'aukera', m: 'Zer dio Platonen dualismo ontologikoak?',
        a: ['Bi errealitate daudela: mundu sentikorra eta ideien mundua', 'Gizakia gorputza eta arima dela', 'Bi ezagutza mota daudela', 'Bi gobernu mota daudela'], z: 0,
        az: 'Dualismo (bi) ontologikoa (errealitatea): mundu sentikorra itxurazkoa da; ideien mundua da benetako errealitatea.' },
      { mota: 'aukera', m: 'Nolakoak dira Platonen ideiak?',
        a: ['Materiagabeak, perfektuak, hilezkorrak eta absolutuak', 'Aldakorrak eta materialak', 'Zentzumenez ezagutzen direnak', 'Gizaki bakoitzaren iritziak'], z: 0,
        az: 'Ideiak molde perfektu eta betierekoak dira, eta arrazoiaren bitartez soilik ezagutzen dira, ez zentzumenez.' },
      { mota: 'aukera', m: 'Zaldi guztiak ezberdinak dira, baina denak zaldiak direla badakigu. Zergatik, Platonen ustez?',
        a: ['Denek zaldiaren ideia (esentzia) partekatzen dutelako', 'Denak kolore berekoak direlako', 'Zentzumenek beti engainatzen gaituztelako', 'Hitz bera erabiltzen dugulako, besterik ez'], z: 0,
        az: 'Mundu sentikorreko izate guztiak ideien munduko moldeetatik sortuak dira, eta oinarrizko esentzia hori partekatzen dute.' },
      { mota: 'aukera', m: 'Platonentzat, zein da ideia guztietatik gorena?',
        a: ['Ongiaren ideia', 'Edertasunaren ideia', 'Zaldiaren ideia', 'Zenbakiaren ideia'], z: 0,
        az: 'Ongiaren ideia da gorena eta gizakiak azkena ezagutzen duena. Filosofoek soilik ezagutzen dute.' },
      { mota: 'aukera', m: 'Platonen dualismo epistemologikoan, nola deitzen zaio zentzumenen bidezko ezagutzari?',
        a: ['Doxa (iritzia)', 'Episteme (zientzia)', 'Dialektika', 'Aretē'], z: 0,
        az: 'Zentzumenen edukiei buruz iritziak (doxa) baino ez ditugu. Benetako ezagutza (episteme) arrazoimenaren bidez lortzen da.' },
      { mota: 'aukera', m: 'Haitzuloaren alegorian, zer adierazten dute horman ikusten diren itzalek?',
        a: ['Zentzumenez hautematen dugun mundu aldakorra (iritzia)', 'Ideien mundua', 'Ongiaren ideia', 'Arima hilezkorra'], z: 0,
        az: 'Jaiotzean haitzuloko presoak bezalakoak gara: itzalak (mundu sentikorra) errealak direla sinesten dugu.' },
      { mota: 'aukera', m: 'Haitzuloaren alegorian, zer da eguzkia?',
        a: ['Ongiaren ideia', 'Mundu sentikorra', 'Filosofo agintaria', 'Arimaren zati irritsua'], z: 0,
        az: 'Eguzkiak mundu sentikorra argitzen duen bezala, Ongiaren ideiak beste ideia guztiak egiten ditu ikusgarri.' },
      { mota: 'aukera', m: 'Zerk askatzen ditu presoak kateetatik haitzuloaren alegorian?',
        a: ['Heziketak, ikasketa-prozesuak: dialektikak', 'Zentzumenek', 'Jainkoek', 'Legeek'], z: 0,
        az: 'Heziketak burua biratzen laguntzen digu: arrazoia erabiliz, itzalak utzi eta ideiak ezagutzera iristen gara.' },
      { mota: 'aukera', m: 'Zein da Platonen ezagutzaren bidearen ordena zuzena?',
        a: ['Pertzepzioa → zentzuzko sinesmena → matematika → dialektika', 'Dialektika → matematika → pertzepzioa → sinesmena', 'Zentzuzko sinesmena → pertzepzioa → dialektika → matematika', 'Matematika → pertzepzioa → dialektika → sinesmena'], z: 0,
        az: 'Bidea goranzkoa da: lehen bi etapak iritzia (doxa) dira; hirugarrenean (matematika) zientziara (episteme) igarotzen gara; laugarrenean, dialektikaren bidez, ideiak eskuratzen dira.' },
      { mota: 'aukera', m: 'Zer da dialektika Platonentzat?',
        a: ['Elkarrizketa arrazoituaren bidez pentsatzeko artea', 'Jendea konbentzitzeko artea', 'Zentzumenen bidezko behaketa', 'Zenbakiak kalkulatzeko teknika'], z: 0,
        az: 'Dialektika da ideiak ezagutzeko bidea. Ideiak ezin dira irakatsi: bakoitzak intuizioz eskuratzen ditu, arrazoizko diskurtsoan trebatuz.' },
      { mota: 'aukera', m: 'Zer dio Platonen oroitzapenaren teoriak?',
        a: ['Ezagutzea arimak ideien munduan ezagututakoa gogoratzea dela', 'Arima hutsik jaiotzen dela', 'Esperientziak ematen dizkigula ezagutza guztiak', 'Ezer ezin dela ezagutu'], z: 0,
        az: 'Arimak, gorputzean erori aurretik, ideia guztiak ezagutu zituen. Dialektikaren bidez pixkanaka gogoratzen ditu.' },
      { mota: 'aukera', m: 'Aristotelesentzat, zenbat errealitate edo mundu daude?',
        a: ['Bat: mundu sentikorra', 'Bi: ideien mundua eta mundu sentikorra', 'Hiru: begetatiboa, sentimenezkoa eta arrazionala', 'Bat ere ez: dena itxura da'], z: 0,
        az: 'Aristotelesek ukatu egin zuen naturaz gaindiko bigarren mundu bat zegoenik: mundu sentikorra da errealitate bakarra.' },
      { mota: 'aipua', m: '"Ez dago ezer gure adimenean, lehenago gure zentzumenetatik pasa ez denik."',
        a: ['Aristoteles', 'Platon', 'Parmenides', 'Pitagoras'], z: 0,
        az: 'Aristotelesentzat esperientziak ematen dizkigu ezagutzak: zentzumenak dira mundua ezagutzeko iturririk baliagarriena.' },
      { mota: 'aukera', m: 'Zer dio hilemorfismoak?',
        a: ['Existitzen den guztia materiaz eta formaz osatuta dagoela', 'Arima gorputzaren kartzela dela', 'Bi mundu daudela', 'Dena atomoz osatuta dagoela'], z: 0,
        az: 'Materia eta forma ez dira bi gauza independente: sustantzia baten bi osagai banaezinak dira.' },
      { mota: 'aukera', m: 'Aristotelesen arabera, arraultza bat txita da...',
        a: ['potentzian', 'egintzan', 'akzidentean', 'ideien munduan'], z: 0,
        az: 'Arraultza arraultza da egintzan (orain dena), baina txita potentzian (izan daitekeena). Hala azaltzen du Aristotelesek aldaketa.' },
      { mota: 'aukera', m: '"Txakur zuri hura": zein akzidente kategoria da "zuri"?',
        a: ['Kalitatea', 'Kantitatea', 'Lekua', 'Erlazioa'], z: 0,
        az: 'Akzidenteak sustantziaren momentuko ezaugarriak dira (9 kategoria). Ez dute esentzia aldatzen: txakurrak txakur izaten jarraitzen du kolorea aldatuta ere.' },
      { mota: 'aukera', m: 'Doriforoaren eskulturan, zer kausa da eskultorea?',
        a: ['Kausa eraginkorra (motorra)', 'Kausa materiala', 'Kausa formala', 'Kausa xedezkoa'], z: 0,
        az: 'Kausa eraginkorra sustantzia potentziatik egintzara mugiarazten duen agentea da. Marmola: kausa materiala; atletaren itxura: formala; oroigarri izatea: xedezkoa.' },
      { mota: 'aukera', m: 'Doriforoaren eskultura hildako atleta baten oroigarri izateko egin zen. Zer kausa da hori?',
        a: ['Kausa xedezkoa', 'Kausa materiala', 'Kausa eraginkorra', 'Kausa formala'], z: 0,
        az: 'Kausa xedezkoak azaltzen du zertarako sortu den zerbait. Aristotelesen ikuspegi teleologikoan (telos = helburua) dena dago xede baterantz.' },
      { mota: 'aukera', m: 'Platonen eta Aristotelesen tradizioei nola deitzen zaie, hurrenez hurren?',
        a: ['Idealismo platonikoa eta errealismo aristotelikoa', 'Errealismo platonikoa eta idealismo aristotelikoa', 'Eszeptizismoa eta estoizismoa', 'Monismoa eta pluralismoa'], z: 0,
        az: 'Maisu eta ikasle izan arren, erantzun ezberdinak eman zituzten: hortik datoz bi tradizio handiak.' }
    ]
  },

  // ===================================================================
  {
    id: 'polis', zenbakia: 4, izena: 'Polis',
    gaia: 'Etika eta politika: Platon eta Aristoteles',
    ikonoa: '⚖️', kolorea: '#7c5cff',
    deskribapena: 'Ongia, arima, bertuteak, hiri ideala eta gobernu motak.',
    galderak: [
      { mota: 'aukera', m: 'Platonentzat, zein da heziketaren helbururik garrantzitsuena?',
        a: ['Bertutetsua izatea (aretē)', 'Aberastea', 'Ondo hitz egiten ikastea', 'Gorputza lantzea'], z: 0,
        az: 'Arrazoiaren eta dialogoaren bidez, norberak barruan dituen ideiak ezagutu behar ditu, Ongiaren ideiara iritsi arte.' },
      { mota: 'aukera', m: 'Platonen "espirituzko aristokrazian", nork gobernatzen du?',
        a: ['Filosofoek', 'Soldaduek', 'Herritar guztiek', 'Aberatsenek'], z: 0,
        az: 'Filosofoek soilik ezagutzen dute Ongiaren ideia, eta horregatik dakite hiria justuki gobernatzen.' },
      { mota: 'aukera', m: 'Zer dio Platonen dualismo antropologikoak?',
        a: ['Gizakia bi atalez osatua dagoela: gorputza eta arima', 'Bi errealitate daudela', 'Bi ezagutza mota daudela', 'Bi gizarte-klase daudela'], z: 0,
        az: 'Antropologia = gizakia. Arima jainkozkoa, betierekoa eta hilezkorra da; gorputza, hilkorra eta ustelkorra.' },
      { mota: 'aukera', m: 'Platonentzat, zer da gorputza?',
        a: ['Arimaren kartzela', 'Arimaren forma', 'Benetako errealitatea', 'Ezagutzaren iturri nagusia'], z: 0,
        az: 'Gorputza materiaduna da eta mundu sentikorrekoa; arima, materiagabea eta ideien mundukoa.' },
      { mota: 'aukera', m: 'Zer da "eros" Platonentzat?',
        a: ['Arimak ideien mundura itzultzeko duen desioa (maitasuna)', 'Gorputzaren plazera', 'Arimaren zati irritsua', 'Hiriko gobernu mota bat'], z: 0,
        az: 'Erosek bultzatzen du gizakia, arrazoia erabiliz, iraganean ezagututako kontzeptu unibertsalak berreskuratzera.' },
      { mota: 'aukera', m: 'Arimaren suminezko zatia: non dago eta zein da bere bertutea?',
        a: ['Bularraldean; ausardia', 'Sabelean; neurritasuna', 'Buruan; jakituria', 'Bularraldean; neurritasuna'], z: 0,
        az: 'Suminezko zatia emozioekin, borondatearekin eta adorearekin lotua dago, eta bere bertutea ausardia da.' },
      { mota: 'aukera', m: 'Zein bertute dagokio arimaren zati irritsuari (sabela)?',
        a: ['Neurritasuna', 'Ausardia', 'Jakituria', 'Justizia'], z: 0,
        az: 'Zati irritsua desioarekin, pasioarekin eta bulkadekin lotua dago. Neurritasuna desioen gaineko kontrola da.' },
      { mota: 'aukera', m: 'Platonen hiri idealean, zein klase lotzen da arimaren suminezko zatiarekin?',
        a: ['Zaintzaileak (soldaduak)', 'Gobernariak (filosofoak)', 'Produktugileak', 'Esklaboak'], z: 0,
        az: 'Gobernariak ↔ zati arrazionala (zuhurtzia); zaintzaileak ↔ suminezkoa (sendotasuna); produktugileak ↔ irritsua (neurritasuna).' },
      { mota: 'eg', m: 'Platonen hiri idealean, gobernariek eta zaintzaileek ezin dute ez jabetzarik ez familiarik izan.',
        a: ['Egia', 'Gezurra'], z: 0,
        az: 'Egia. Distrakzioak baino ez lirateke kargu garrantzitsuak dituztenentzat. Estatua arduratzen da ezkontzez eta umeen heziketaz.' },
      { mota: 'aukera', m: 'Platonentzat, noiz da hiri bat justua?',
        a: ['Klase bakoitzak bere betebeharra betetzen duenean (harmonia)', 'Denek gauza bera egiten dutenean', 'Aberastasuna berdin banatzen denean', 'Gehiengoak bozkatzen duenean'], z: 0,
        az: 'Arimaren hiru zatiak orekatu behar diren bezala, klase bakoitzak bere egitekoa betetzen badu, ordena eta harmonia nagusituko dira.' },
      { mota: 'aukera', m: 'Aristotelesen ustez, zer da arima?',
        a: ['Gorputzaren forma: bizitzaren printzipioa', 'Gorputzetik bereizitako sustantzia', 'Ideien mundutik erori den izatea', 'Atomo multzo bat'], z: 0,
        az: 'Eskema hilemorfikoan, gorputza materia da (potentzia) eta arima forma (egintza). Ezin da arima gorputzik gabe existitu.' },
      { mota: 'aukera', m: 'Aristotelesen arabera, zein arima mota dituzte animaliek?',
        a: ['Begetatiboa eta sentimenezkoa', 'Begetatiboa soilik', 'Hirurak: begetatiboa, sentimenezkoa eta arrazionala', 'Arrazionala soilik'], z: 0,
        az: 'Landareek arima begetatiboa dute; animaliek, begetatiboa eta sentimenezkoa; gizakiak, hirurak (arrazionala barne).' },
      { mota: 'eg', m: 'Aristotelesen ustez, arima ideia unibertsalekin jaiotzen da.',
        a: ['Egia', 'Gezurra'], z: 1,
        az: 'Gezurra. Aristotelesentzat arima hutsik jaiotzen da, "zuri-zurian". Ezagutza zentzumenetatik abiatzen da, ez oroitzapenetik.' },
      { mota: 'aukera', m: 'Aristotelesentzat, zein da gizakiaren azken helburua (azken ongia)?',
        a: ['Zoriontasuna (eudaimonia)', 'Plazera', 'Boterea', 'Aberastasuna'], z: 0,
        az: 'Ikuspegi teleologikoan izate orok bere helburura jotzen du. Gizakiaren kasuan, zoriontasuna da, bertutetsu jokatuz lortzen dena.' },
      { mota: 'aukera', m: '"Adorea beldurraren eta ausarkeriaren arteko erdigune justua da." Zein bertute motari dagokio?',
        a: ['Bertute moralei (etikoei)', 'Bertute intelektualei (dianoetikoei)', 'Arima begetatiboari', 'Ideien munduari'], z: 0,
        az: 'Bertute moralak ohituraz eta praktikaz lortzen dira: gabeziaren eta gehiegikeriaren arteko erdibidea aurkitzea, arrazoiak gidatuta.' },
      { mota: 'aipua', m: '"Gizakia animalia politikoa da."',
        a: ['Aristoteles', 'Platon', 'Sokrates', 'Zenon'], z: 0,
        az: 'Gizakia ezin da gizartetik kanpo bizi. Aristotelesentzat elkarterik garrantzitsuena familia da; gero auzoa, eta azkenik hiria.' },
      { mota: 'aukera', m: 'Aristotelesen arabera, aristokrazia usteltzen denean zer bihurtzen da?',
        a: ['Oligarkia', 'Tirania', 'Demagogia', 'Monarkia'], z: 0,
        az: 'Monarkia → tirania; aristokrazia → oligarkia; errepublika → demagogia. Gobernu okerrek agintarien interes pertsonalak bultzatzen dituzte.' },
      { mota: 'aukera', m: 'Aristotelesentzat, zein da gobernu-sistemarik onena?',
        a: ['Erdiko klase batek gidatutako errepublika', 'Filosofoen aristokrazia', 'Monarkia absolutua', 'Aberatsen oligarkia'], z: 0,
        az: 'Politikariak ez lirateke oso aberatsak ez pobreak izan behar, eta hiritar guztiek har dezakete parte, merezimenduaren arabera.' },
      { mota: 'aukera', m: 'Zuzen jokatzeko, zer behar da Aristotelesen ustez, ongia ezagutzeaz gain?',
        a: ['Borondatea eta ohitura onak', 'Ezer ez: jakitea nahikoa da', 'Jainkoen laguntza', 'Aberastasuna'], z: 0,
        az: 'Hemen Aristoteles ez dator bat Sokrates eta Platonen intelektualismo moralarekin: jakitea ez da nahikoa, borondatea ere behar da.' },
      { mota: 'aukera', m: 'Aristotelesen arabera, zein bi baldintza bete behar ditu hiri batek justua izateko?',
        a: ['Legezkotasuna eta merezimendua', 'Harmonia eta oreka', 'Aberastasuna eta boterea', 'Askatasuna eta berdintasuna'], z: 0,
        az: 'Hiritar guztiek bete behar dute legea, eta legea ez da oligarkikoa ez demokratikoa izan behar, tarteko zerbait baizik.' }
    ]
  },

  // ===================================================================
  {
    id: 'alejandria', zenbakia: 5, izena: 'Alejandria',
    gaia: 'Helenismoa: zinismoa, estoizismoa, epikureismoa, eszeptizismoa',
    ikonoa: '📜', kolorea: '#30a46c',
    deskribapena: 'Polisetik inperiora: filosofia bizitzaren arte gisa.',
    galderak: [
      { mota: 'aukera', m: 'Aristotelesen heriotzaz geroztik, zein erreinu gailendu zen Greziako potentzien gainetik?',
        a: ['Mazedonia', 'Persia', 'Egipto', 'Esparta'], z: 0,
        az: 'Alejandro Magnok (K.a. 356-323) Persia eta Siriatik Indiaraino eta Egiptoraino zabaldu zituen konkistak, eta kultura grekoa hedatu zen.' },
      { mota: 'aukera', m: 'Zer da sinkretismoa?',
        a: ['Kultura ezberdinen arteko bateratze edo elkartruke erlijiosoa', 'Plazerra bilatzeko metodoa', 'Judizioa eteteko jarrera', 'Hiri-estatuen arteko gerra'], z: 0,
        az: 'Mediterraneoko eta ekialdeko ideiak nahastu ziren, eta korronte erlijioso berriak sortu ziren.' },
      { mota: 'aukera', m: 'Zein hiri bihurtu zen Helenismoko zentro intelektual eta zientifiko handiena, museo eta liburutegi ospetsuekin?',
        a: ['Alejandria', 'Atenas', 'Erroma', 'Mileto'], z: 0,
        az: 'Alejandrian (Egipto) garatu ziren astronomia, matematika, biologia eta medikuntza, inperio osoko pentsalariak bilduta.' },
      { mota: 'aukera', m: 'Helenismoan, nola ulertzen zen filosofia?',
        a: ['"Bizitzaren arte" gisa: zoriontasuna eta askatasuna lortzeko tresna', 'Naturaren arkhea bilatzeko zientzia gisa', 'Erretorika-ikastaro gisa', 'Matematikaren adar gisa'], z: 0,
        az: 'Pentsalariak arazo existentzial eta pertsonaletan zentratu ziren: angustiari, heriotzaren beldurrari eta etsipenari aurre egitea.' },
      { mota: 'aukera', m: 'Nork bultzatu zuen zinismoa, Sokratesen bizimodu apalaz miretsita?',
        a: ['Antistenesek', 'Epikurok', 'Zenonek', 'Pirronek'], z: 0,
        az: 'Antistenes Sokratesen dizipulua izan zen. "Zoriontasuna beharrak murriztean datza, jabetzak handitzean baino gehiago."' },
      { mota: 'aipua', m: '"Egin zaitez albo batera, eguzkia estaltzen didazu."',
        a: ['Diogenes Sinopekoa', 'Seneka', 'Epikuro', 'Marko Aurelio'], z: 0,
        az: 'Diogenesek horrela erantzun zion Alejandro Handiari, nahi zuena eskatzeko esan zionean.' },
      { mota: 'aukera', m: 'Non bizi zen Diogenes Sinopekoa?',
        a: ['Atenasko kale-bazter bateko upel batean', 'Jauregi batean', 'Lorategi batean', 'Alejandriako liburutegian'], z: 0,
        az: 'Muturreko pobrezian bizi zen. Ume bat eskuekin ura edaten ikusi zuenean, katilua bota zuen: "Ume batek gainditu nau sinpletasunean".' },
      { mota: 'aukera', m: 'Zer da "parresia" zinikoentzat?',
        a: ['Zintzotasun erradikala: pentsatzen dena esatea', 'Gorputzaren minaren ausentzia', 'Destinoaren onarpena', 'Judizioaren etetea'], z: 0,
        az: 'Zinikoek iritzi-askatasun erradikala defendatzen zuten, konbentzioei eta autoritateari men egin gabe.' },
      { mota: 'aukera', m: 'Nondik dator "estoizismo" izena?',
        a: ['Stoa-tik: Zenonek irakasten zuen arkupedun ataritik', 'Estoiko izeneko filosofo batetik', 'Grezierazko "lasaitasuna" hitzetik', 'Alejandriako auzo batetik'], z: 0,
        az: 'Zenon Zitiokoak, estoizismoaren sortzaileak, Atenasen irakatsi zuen, stoa deituriko ataripe baten azpian.' },
      { mota: 'aukera', m: 'Zer da "amor fati" estoikoentzat?',
        a: ['Destinoaren onarpena', 'Plazeraren bilaketa', 'Ondasun materialen ukapena', 'Zintzotasun erradikala'], z: 0,
        az: 'Gertatzen zaiguna ez dugu kontrolatzen; bai, ordea, nola erantzuten diogun. Jakintsuak patxadaz onartzen du destinoa.' },
      { mota: 'aipua', m: '"Alda ezazu alda dezakezuna eta onartu ezazu alda ezin dezakezuna."',
        a: ['Marko Aurelio', 'Diogenes', 'Epikuro', 'Pirron'], z: 0,
        az: 'Marko Aurelio enperadore estoikoa izan zen. Amor fati: destinoa onartu eta gure erantzuna gobernatu.' },
      { mota: 'aipua', m: '"Gehien kezkatzen gaituen hori edo aspaldi jazo zen, edo oraindik ez da jazo, edo ez da sekula jazoko."',
        a: ['Seneka', 'Sokrates', 'Antistenes', 'Demokrito'], z: 0,
        az: 'Seneka estoikoa: alferrikakoa da gure eskuetan ez dagoenaz kezkatzea.' },
      { mota: 'eg', m: 'Estoikoek, zinikoek bezala, politika baztertu zuten.',
        a: ['Egia', 'Gezurra'], z: 1,
        az: 'Gezurra. Humanismo unibertsalaren ondorioz, komunitatearen ongizateaz arduratu ziren: Marko Aurelio, Seneka eta Zizeron gobernuburu izan ziren.' },
      { mota: 'aukera', m: 'Gaur egun zein terminok adierazten du estoikoek aldarrikatzen zutena: aurkako egoerei positiboki erantzuteko gaitasuna?',
        a: ['Erresilientzia', 'Enpatia', 'Errendimendua', 'Asertibitatea'], z: 0,
        az: 'Barne-sendotasuna, arrazoizko jokaera eta pasioen kontrola ziren estoikoen gakoak, eta neurritasuna oinarrizko bertutea.' },
      { mota: 'aukera', m: 'Nola deitzen zen Epikurok Atenasen sortu zuen eskola, emakumeei eta esklaboei ere irekia?',
        a: ['Lorategia', 'Stoa', 'Akademia', 'Lizeoa'], z: 0,
        az: 'Epikuro (K.a. 341-270) Samosen jaio zen eta "Lorategia" eskolan irakatsi zuen.' },
      { mota: 'eg', m: 'Epikureoentzat, bizitzaren helburua plazer sentsual eta neurrigabea da.',
        a: ['Egia', 'Gezurra'], z: 1,
        az: 'Gezurra. Plazerak arrazionala izan behar du, tentaldian eta adikzioan erori gabe. Giza harremanak luxuaren eta boterearen gainetik daude.' },
      { mota: 'aukera', m: 'Zer da ataraxia?',
        a: ['Arimaren lasaitasuna: ezinegonik eta beldurrik eza', 'Gorputzaren minaren ausentzia', 'Isilik geratzea', 'Destinoaren onarpena'], z: 0,
        az: 'Ataraxia espirituaren lanketa da. Estoikoek, epikureoek eta eszeptikoek aldarrikatu zuten.' },
      { mota: 'aukera', m: 'Zer da aponia epikureoentzat?',
        a: ['Gorputzaren minaren ausentzia', 'Arimaren lasaitasuna', 'Judiziorik gabeko esperientzia', 'Zintzotasun erradikala'], z: 0,
        az: 'Gorputza zaindu behar da, bizitza honetako ibilgailua delako: bizitza osasungarria funtsezkoa da zoriontsu izateko.' },
      { mota: 'aukera', m: 'Zein filosoforen irakaspenei jarraitzen zieten eszeptikoek?',
        a: ['Pirron', 'Epikuro', 'Antistenes', 'Zenon'], z: 0,
        az: 'Pirronen (K.a. 360-270) ustez ezer ezin da benetan ezagutu: zentzumenek gauzen itxura baino ez dute antzematen.' },
      { mota: 'aukera', m: 'Eszeptikoentzat, zer da "epokhē"?',
        a: ['Judiziorik gabeko esperientziak izatea (judizioa etetea)', 'Isilik mantentzea', 'Minaren ausentzia', 'Destinoa onartzea'], z: 0,
        az: 'Ezer ez denez ziurra, hobe da judizioa etetea (epokhē) eta eztabaidetan isilik mantentzea (afasia), ataraxia lortzeko.' }
    ]
  },

  // ===================================================================
  {
    id: 'olinpo', zenbakia: 6, izena: 'Olinpo',
    gaia: 'Azken froga: gai guztiak nahasian',
    ikonoa: '⚡', kolorea: '#ff8a3d',
    deskribapena: 'Bost gaien galderak nahasian, eta filosofoak elkarrekin alderatzeko galdera bereziak.',
    nahasia: true,     // beste mailetako galderak ere hartzen ditu
    galderak: [
      { mota: 'aukera', m: 'Zein da ordena kronologiko zuzena?',
        a: ['Tales → Sokrates → Aristoteles → Epikuro', 'Sokrates → Tales → Epikuro → Aristoteles', 'Tales → Aristoteles → Sokrates → Epikuro', 'Epikuro → Tales → Sokrates → Aristoteles'], z: 0,
        az: 'Tales (K.a. 639-547), Sokrates (Platonen maisua), Aristoteles (Platonen ikaslea) eta Epikuro (K.a. 341-270, Helenismoa).' },
      { mota: 'aukera', m: 'Aristoteles bat dator presokratiko batekin, naturan dena transformazio eta mugimendu konstantean dagoela esatean. Zeinekin?',
        a: ['Heraklito', 'Parmenides', 'Pitagoras', 'Demokrito'], z: 0,
        az: 'Aristotelesek dio, Heraklitok bezala, naturan dena dagoela mugimenduan: potentziatik egintzara.' },
      { mota: 'aukera', m: 'Zein kontzeptu aldarrikatu zuten estoikoek, epikureoek eta eszeptikoek?',
        a: ['Ataraxia', 'Aponia', 'Parresia', 'Apeirona'], z: 0,
        az: 'Hiru eskolek bilatzen zuten arimaren lasaitasuna, ezinegonik eta kezkarik gabeko adimena.' },
      { mota: 'aukera', m: 'Sofistek erlatibismo morala defendatu zuten. Nork defendatu zuen kontrakoa: antierlatibismo morala?',
        a: ['Sokratesek eta Platonek', 'Gorgiasek', 'Pirronek', 'Diogenesek'], z: 0,
        az: 'Sokratesentzat eta Platonentzat ongia eta justizia unibertsalak eta betierekoak dira, ez erlatiboak.' },
      { mota: 'aukera', m: 'Zein korrontek lehenetsi zituen giza harremanak (adiskidetasuna, familia) luxuaren gainetik, eta uko egin politikan parte hartzeari?',
        a: ['Epikureismoak', 'Estoizismoak', 'Sofistek', 'Pitagorikoek'], z: 0,
        az: 'Epikureoentzat politikak kezka, beldur eta ustelkeria dakartza. Estoikoek, aldiz, ez zuten politika baztertu.' },
      { mota: 'aukera', m: 'Zinikoek eta Sokratesek zer zuten komunean?',
        a: ['Bizimodu apala eta ondasun materialen ukapena', 'Erretorikarengatik kobratzea', 'Bi munduren teoria', 'Atomoetan sinestea'], z: 0,
        az: 'Sokratesek ez zuen kobratzen bere irakaspenengatik eta ondasun materialak baztertzen zituen. Antistenes miretsita geratu zen.' },
      { mota: 'aukera', m: 'Ezagutzari dagokionez, zertan ez datoz bat Platon eta Aristoteles?',
        a: ['Platonentzat ezagutza oroitzapena da; Aristotelesentzat zentzumenetatik abiatzen da', 'Platonentzat zentzumenak fidagarriak dira; Aristotelesentzat ez', 'Biek uste dute arima hutsik jaiotzen dela', 'Ez dago desadostasunik'], z: 0,
        az: 'Idealismo platonikoa (ideiak arrazoiaz eta oroitzapenez) eta errealismo aristotelikoa (esperientziatik abiatuta).' },
      { mota: 'aukera', m: 'Zein bikote dago gaizki lotuta?',
        a: ['Anaximenes – sua', 'Tales – ura', 'Pitagoras – zenbakiak', 'Demokrito – atomoak'], z: 0,
        az: 'Anaximenesentzat airea zen arkhea, ez sua.' }
    ]
  }
];
